install.packages("knitr")
install.packages("readr")
library(knitr)
library(readr)
data_with_lat <- read_csv("~/data with lat.csv")
View (data_with_lat)
head(data_with_lat)
install.packages("ggplot2")
install.packages("ggmap")
library (ggplot2)
library(ggmap)
ggplot(aes(x=lon, y=lat), data=df)
geocode("Baltimore")
ggmap("Baltimore")
theme_set(theme_bw(16))
BaltimoreMap <- qmap("Baltimore", zoom = 13, color = "bw", legend = "topleft")

